In [1]:
import pandas as pd
print(pd.__version__)

1.0.1


In [2]:
# play w/ pandas concat/append

In [3]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                      'D': ['D2', 'D3', 'D6', 'D7'],
                      'F': ['F2', 'F3', 'F6', 'F7']},
                      index=[2, 3, 6, 7])

In [4]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])

In [5]:
pd.concat([df1,df4],join='outer',axis=1,sort=False)

A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [6]:
dfM=pd.concat([df1,df4],join='outer',axis=1,sort=False)
dfM.columns  # column name can be reused!

Index(['A', 'B', 'C', 'D', 'B', 'D', 'F'], dtype='object')

In [7]:
pd.concat([df1,df4],join='outer',axis=0,sort=False)

A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [8]:
dfR = pd.concat([df1,df4],join='outer',axis=0,sort=False)
dfR.index # same thing: you can re-use a row index also

Int64Index([0, 1, 2, 3, 2, 3, 6, 7], dtype='int64')

In [10]:
print(dfM['A'])
print(type(dfM.A))
print(dfM.B)
print(type(dfM.B))
print(dfR.loc[0])
print(type(dfR.loc[0]))
print(dfR.loc[2])
print(type(dfR.loc[2]))

# Yikes. Data type depends on multiplicity. Bottom line: need to be very careful with concat !!!!!!!!!!!!!!!!!!!!

0     A0
1     A1
2     A2
3     A3
6    NaN
7    NaN
Name: A, dtype: object
<class 'pandas.core.series.Series'>
     B    B
0   B0  NaN
1   B1  NaN
2   B2   B2
3   B3   B3
6  NaN   B6
7  NaN   B7
<class 'pandas.core.frame.DataFrame'>
A     A0
B     B0
C     C0
D     D0
F    NaN
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
     A   B    C   D    F
2   A2  B2   C2  D2  NaN
2  NaN  B2  NaN  D2   F2
<class 'pandas.core.frame.DataFrame'>


In [11]:
df1.append(df4)

A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [12]:
df1
# it's still the original df1

# note: behaves unlike list method append()
    # list append():
        # appends inplace and returns None
    # pandas append():
        # makes a full copy of the data, returns a new dataframe, retains original dfs in the original vars
        

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [14]:
x = 'eroig'
import re as x
print(x)
# overwrites x

<module 're' from 'C:\\Users\\rek\\Anaconda3\\envs\\lightwave\\lib\\re.py'>


In [15]:
import re

In [16]:
getattr(re,'findall')

<function re.findall(pattern, string, flags=0)>

In [18]:
re.findall('w\wg','wegtriowwghiuheiurhgeirughew9gwagwwgg')


['weg', 'wwg', 'w9g', 'wag', 'wwg']

In [20]:
getattr(globals()['re'],'findall')('w\wg','wegtriowwghiuheiurhgeirughew9gwagwwgg')

# Nice!

# meta-programming is definitely possible here !!!!

['weg', 'wwg', 'w9g', 'wag', 'wwg']

In [21]:
globals()['re']

<module 're' from 'C:\\Users\\rek\\Anaconda3\\envs\\lightwave\\lib\\re.py'>

In [22]:
('re' in globals())

True

In [23]:
import calendar
print(calendar.monthrange(2020,2))

(5, 29)


In [24]:
import datetime

In [25]:
globals()['datetime']

<module 'datetime' from 'C:\\Users\\rek\\Anaconda3\\envs\\lightwave\\lib\\datetime.py'>

In [26]:
getattr(getattr(globals()['datetime'],'datetime'),'strptime')('06/21/2020','%m/%d/%Y')

# Nice. You can chain the getattrs together ... so you won't need to know a priori how many levels deep it goes 

datetime.datetime(2020, 6, 21, 0, 0)

In [28]:
L_FS='datetime.datetime.strptime'.split('.')[::-1]
M=L_FS.pop()
print((M,L_FS))
# lists pop from the end, must be reversed if you want pop to remove the first element

('datetime', ['strptime', 'datetime'])


In [29]:
def myMeta(funcString,arg1,arg2):
    # should use args and kwargs eventually
        # but I'll test this way for now, b/c both re.findall() and datetime.datetime.strptime() each take exactly 2 args
    L_FS = funcString.split('.')[::-1]
    myFunction = globals()[L_FS.pop()]  # at level 1, this is the base module reference
    while L_FS:
        myFunction = getattr(myFunction,L_FS.pop())
    return myFunction(arg1,arg2)

In [30]:
print(myMeta('re.findall','w\wg','wegtriowwghiuheiurhgeirughew9gwagwwgg'))
print(myMeta('datetime.datetime.strptime','06/21/2020','%m/%d/%Y'))
print(myMeta('calendar.monthrange',2020,2))


['weg', 'wwg', 'w9g', 'wag', 'wwg']
2020-06-21 00:00:00
(5, 29)


In [31]:
# Okay awesome, it works!

In [32]:
# you do still need to import each library upfront.
            # Is there a meta way to do imports also?
                    # Regardless, I don't actually need to answer this for the current task
                        # and I don't wish to allow random libraries to be imported
                                # 1) seems too risky (security etc.)
                                # 2) might not even be installed in the eventual environment / compiler anyway !

In [33]:
print(myMeta('pow',3,7))
# single-word from builtins doesn't work 

KeyError: 'pow'

In [34]:
print(pow(3,7))
print(myMeta('builtins.pow',3,7))   # you could try using pow referenced from 'builtins'? But that's not in globals()

2187


KeyError: 'builtins'

In [35]:
# so you will have to explicity import that module first

import builtins
print(myMeta('builtins.pow',3,7))
# now it works

2187


In [36]:
# Okay now let us try to write a Meta Func that accepts an arbitary number of arguments:

# metaA   !!!!

In [37]:
def metaA(funcString,*args,**kwargs):
    L_FS = funcString.split('.')[::-1]
    myFunction = globals()[L_FS.pop()]  # at level 1, this is the base module reference
    while L_FS:
        myFunction = getattr(myFunction,L_FS.pop())
    return myFunction(*args,**kwargs)

In [38]:
print(metaA('calendar.monthrange',2020,2))
print(metaA('re.findall','\d+','23tt345erg43e23we233wew32'))
print(metaA('datetime.datetime.strptime','06/21/2020','%m/%d/%Y'))  #$ works for a module nested deeper
print(metaA('builtins.pow',3,7))              # works for builtin func, but you do need to explicitly import from builtins!

(5, 29)
['23', '345', '43', '23', '233', '32']
2020-06-21 00:00:00
2187


In [39]:
# it works for arbitary number of arguments !
qwe = metaA('re.compile','\d+')
print(re.findall(qwe,'23tt345erg43e23we233wew3242'))   # works for just one arg
metaA('builtins.print','a','b','c','d','e','f','g','h','i','j')     # works for ten args !
                # note: don't nest this print inside another print, or else it will write another 'None' to the output stream

['23', '345', '43', '23', '233', '3242']
a b c d e f g h i j


In [40]:
# also it works for keyword arguments !
import numpy as np
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=2,axis=1))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=2,axis=0))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=1,axis=1))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=1,axis=0))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=50,axis=1))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),axis=0,ord=50))  # order of kwargs doesn't matter
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),ord=2,axis=1))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),keepdims=True,ord=2,axis=1))
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),2,1,True))       
print(metaA('np.linalg.norm',np.array([[3,4],[3,4]]),2,keepdims=True,axis=1))    # can mix args and kwargs too

[5. 5.]
[4.24264069 5.65685425]
[7. 7.]
[6. 8.]
[4.00000005 4.00000005]
[3.04187844 4.05583792]
[5. 5.]
[[5.]
 [5.]]
[[5.]
 [5.]]
[[5.]
 [5.]]


In [41]:
# Okay awesome.

# But Let me remind myself WHY I am learning this

# because I want maximum design flexibility for sleeky

# want to be able to implement a variety of functions, regardless of their native design,
                # merely by reading and parsing strings that were written into an Excel file !
    

In [42]:
qwe = metaA('re.compile','\d+$')
print(re.findall(qwe,'23tt345erg43e23we233wew3242a'))  
print(re.findall(qwe,'23tt345erg43e23we233wew3242'))   # works for just one arg
print(re.findall(qwe,'23tt345erg43e23we233wew3242 77'))   # works for just one arg

[]
['3242']
['77']


In [43]:
print(re.search('\d+','23tt345erg43e23we233wew3242 77'))
print(getattr(re.search('\d+','23tt345erg43e23we233wew3242 77'),'group')(0))
print(re.search('\d+$','23tt345erg43e23we233wew3242 77'))
print(getattr(re.search('\d+$','23tt345erg43e23we233wew3242 77'),'group')(0))

print()

<re.Match object; span=(0, 2), match='23'>
23
<re.Match object; span=(28, 30), match='77'>
77



In [44]:
print(re.search('\d+$','23tt345erg43e23we233wew3242 77s'))
print(getattr(re.search('\d+$','23tt345erg43e23we233wew3242 77s'),'group')(0))

None


AttributeError: 'NoneType' object has no attribute 'group'

In [45]:
def regexOneMatch(s,myPattern,default=''):
    # swaps arguments, so that it can be applied to metaA framework
    G = re.search(myPattern,s)
    if G:
        return G[0]
    else:
        return default

In [50]:
print(regexOneMatch('erhgoierhgoi34093h4ogiehrg2930heorihg9324v','\d+'))
print(regexOneMatch('erhgoierhgoi34093h4ogiehrg2930heorihg9324v','\d+$'))  # empty match object, but no error
print(regexOneMatch('erhgoierhgoi34093h4ogiehrg2930heorihg9324','\d+$'))

34093

9324
